package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/Hardcoreaiin/hardcore-ai/frontend/internal/toolchain"
	"github.com/Hardcoreaiin/hardcore-ai/frontend/internal/tools"
	"github.com/Hardcoreaiin/hardcore-ai/frontend/internal/tools/embedded"
)

const mainC = `typedef unsigned int uint32_t;

#define PERIPH_BASE        0x40000000UL
#define AHB1PERIPH_BASE    (PERIPH_BASE + 0x00020000UL)
#define RCC_BASE           (AHB1PERIPH_BASE + 0x3800UL)
#define GPIOD_BASE         (AHB1PERIPH_BASE + 0x0C00UL)

#define RCC_AHB1ENR        (*(volatile uint32_t *)(RCC_BASE + 0x30UL))
#define GPIOD_MODER        (*(volatile uint32_t *)(GPIOD_BASE + 0x00UL))
#define GPIOD_ODR          (*(volatile uint32_t *)(GPIOD_BASE + 0x14UL))

#define RCC_AHB1ENR_GPIODEN (1UL << 3)
#define LED_PIN             12U

void Reset_Handler(void);

__attribute__((section(".isr_vector"), used))
void (* const vector_table[])(void) = {
	(void (*)(void))0x20020000UL,
	Reset_Handler,
};

static void delay(volatile uint32_t ticks) {
	while (ticks--) {
		__asm__ volatile ("nop");
	}
}

void Reset_Handler(void) {
	RCC_AHB1ENR |= RCC_AHB1ENR_GPIODEN;

	GPIOD_MODER &= ~(3UL << (LED_PIN * 2U));
	GPIOD_MODER |=  (1UL << (LED_PIN * 2U));

	for (;;) {
		GPIOD_ODR ^= (1UL << LED_PIN);
		delay(800000U);
	}
}

void _start(void) {
	Reset_Handler();
}
`

const readme = `# STM32 Blink Smoke Project

This project was generated by frontend/scripts/stm_blink_flow.

Target: STM32F4-style GPIOD LED on pin 12, as found on many STM32F4 Discovery
examples. The generated C is intentionally freestanding so the embedded build
tool can compile it without a vendor SDK.
`

func main() {
	var (
		project      = flag.String("project", "stm32-blink-smoke", "workspace project name to create or overwrite")
		arch         = flag.String("arch", "stm32f4", "embedded build arch/chip family")
		skipBuild    = flag.Bool("skip-build", false, "only create files and list the project")
		buildTimeout = flag.Duration("build-timeout", 5*time.Minute, "maximum time to wait for toolchain install/build")
	)
	flag.Parse()

	ctx, cancel := context.WithTimeout(context.Background(), *buildTimeout)
	defer cancel()

	reg, err := newRegistry()
	if err != nil {
		die(err)
	}

	fmt.Println("== STM blink flow smoke test ==")
	mustCall(ctx, reg, "workspace_init", *project)
	mustCall(ctx, reg, "file_write", "main.c", mainC)
	mustCall(ctx, reg, "file_write", "README.md", readme)
	mustCall(ctx, reg, "file_list")

	if *skipBuild {
		fmt.Println("build skipped")
		return
	}

	if err := buildWithRetry(ctx, reg, *arch, "main.c"); err != nil {
		die(err)
	}
}

func newRegistry() (*tools.Registry, error) {
	reg := tools.NewRegistry()
	mgr, err := toolchain.DefaultManager()
	if err != nil {
		return nil, err
	}
	mgr.OnEvent = func(ev toolchain.Event) {
		switch ev.Stage {
		case "download":
			if ev.Total > 0 {
				fmt.Printf("toolchain %s: download %.1f%%\n", ev.Tool, float64(ev.Downloaded)*100/float64(ev.Total))
			} else {
				fmt.Printf("toolchain %s: download %d bytes\n", ev.Tool, ev.Downloaded)
			}
		case "extract", "ready":
			fmt.Printf("toolchain %s: %s\n", ev.Tool, ev.Stage)
		case "error":
			fmt.Printf("toolchain %s: error: %v\n", ev.Tool, ev.Err)
		}
	}

	embedded.RegisterWorkspaceInit(reg)
	embedded.RegisterFileWrite(reg)
	embedded.RegisterFileList(reg)
	embedded.RegisterBuild(reg, mgr)
	return reg, nil
}

func buildWithRetry(ctx context.Context, reg *tools.Registry, arch, entry string) error {
	for {
		result, _, err := call(ctx, reg, "build", arch, entry)
		if err != nil {
			return err
		}

		fmt.Printf("build => %s\n", result)
		switch {
		case strings.HasPrefix(result, "OK:"):
			return nil
		case strings.Contains(result, "toolchain is downloading"):
			if err := sleepContext(ctx, 2*time.Second); err != nil {
				return err
			}
			continue
		case strings.HasPrefix(result, "BUILD FAILED:"):
			return errors.New(result)
		default:
			return nil
		}
	}
}

func mustCall(ctx context.Context, reg *tools.Registry, name string, args ...any) {
	result, artifacts, err := call(ctx, reg, name, args...)
	if err != nil {
		die(fmt.Errorf("%s: %w", name, err))
	}
	fmt.Printf("%s => %s\n", name, result)
	for _, a := range artifacts {
		fmt.Printf("artifact %s/%s => %v\n", name, a.Type, a.Payload)
	}
}

func call(ctx context.Context, reg *tools.Registry, name string, args ...any) (string, []tools.Artifact, error) {
	tool, ok := reg.Get(name)
	if !ok {
		return "", nil, fmt.Errorf("unknown tool %q", name)
	}
	return tool.Execute(ctx, args)
}

func sleepContext(ctx context.Context, d time.Duration) error {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-t.C:
		return nil
	}
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}
